#! /bin/sh
### BEGIN INIT INFO
# Provides: noip
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: noip server
# Description:
### END INIT INFO

case "$1" in
    start)
        echo "starting raspi_monitor"
        # Starte Programm
        python3 -m raspi_monitor &
        ;;
    stop)
        echo "noip wird beendet"
        # Beende Programm
        killall python3
        ;;
    *)
        echo "Benutzt: /etc/init.d/raspi_monitor {start|stop}"
        exit 1
        ;;
esac

exit 0

